# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  # https://wowchemy.com/docs/getting-started/customization/#fonts
  font: 'Native' # "Use device fonts for maximum performance"
  # https://wowchemy.com/docs/getting-started/customization/#change-font-size
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'My personal website - bio, blogs, and more'
    twitter: ''

# Contact (edit or remove options as required)

email: defrann8208@outlook.com

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true


# https://wowchemy.com/docs/getting-started/customization/#custom-footer
footer:
  copyright_license:
    notice: 'This work is licensed under {license}'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
  math:
    enable: true
  diagram:
    enable: true
  privacy_pack:
    enable: false
  repository:
    repo_url: 'https://github.com/nick-cd/personal-site.git'
    content_dir: ''
    repo_branch: main
    editable:
      page: false
      post: false
      book: false
  show_related:
    book: true
    page: false
    post: true
    project: true
    publication: true
    event: true
  reading_time: true
  section_pager: false
  docs_section_pager: true
  sharing: true
  abstract_length: 135
  plugins_js: []
  avatar:
    gravatar: true
    shape: circle
  publications:
    date_format: January 2006
    citation_style: apa
  projects:
    post_view: 2
    publication_view: 2
    talk_view: 2
  breadcrumb:
    page_types:
      book: true
  comments:
    provider: ''
    commentable:
      post: true
      book: true
      project: true
      publication: true
      event: true
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15
  marketing:
    google_analytics: 'UA-201256298-1'
    google_tag_manager: ''
    google_site_verification: 'QfDy3yx5VOqUlH_XJxUXKJdIeBpftDuCWfmyiZzk5aU'
    baidu_site_verification: ''
    baidu_tongji: ''
  cms:
    branch: master
    local_backend: false
  icon:
    pack:
      ai: true
